title = "Igor Baiborodine"
baseURL = "https://www.kiroule.com/"
theme = "bilberry-hugo-theme"

# Generate the robots.txt file for SEO
enableRobotsTXT = true

# Change to one of your content languages definded at the end.
DefaultContentLanguage = "en"

# Enable / Disable Google Analytics statistics for your site
googleAnalytics = "UA-60574401-2"

# Enable / Disable comments on the articles via Disqus.
disqusShortname = "kiroule"

# Enable / Disable open link with a new tab.
[blackfriday]
  hrefTargetBlank = false

[params]
  # Custom CSS / JS modules that will be imported by the template.
  # Files are relative to the static/ directory or a URL.
  # Files are imported in the order they appear here, after
  # theme.css and theme.js, respectively.
  css_modules = []
  js_modules = []

  # Description and meta data for the search engines
  author = "Igor Baiborodine|Игорь Байбородин"
  description = "Igor Baiborodine's Blog|Блог Игоря Байбородина"
  keywords = "devops,linux,docker,virtualization,system administration,cloud computing, python programming"

  # How many articles should be displayed at once?
  paginate = 5

  # Enable / Disable MathJax
  enable_mathjax = false

  # Enable / Disable algolia search
  algolia_search    = true
  algolia_appId     = "NLO8K25GU4"
  algolia_apiKey    = "1ea1d7b821a9feb925c6bed046281341"
  algolia_indexName = "ALGOLIA_INDEX_NAME_PLACEHOLDER"
  # Set this option to false if you want to search within all articles in all languages at once
  algolia_currentLanguageOnly = true

  # Media configuration
    # let hugo automatically resize and crop your images to the correct sizes
    # NB: When enabled the image files get renamed by adding additional information,
    #     even if the image has the correct sizes.
    resizeImages = true

  # Header configuration
    # your subtitle if you want to use any
    subtitle = ""

    # if you want to use gravatar for the header image
    gravatarEMail = ""

    # set an path to the image file you want to use | overwrites gravatar
    customImage = "img/avatar.png"

    # define the icon you want to use for the overlay for the customImage or gravatar.
    overlayIcon = "fa-home"

    # always display the top navigation (with pages and search) on non-mobile screens
    permanentTopNav = true

    # always display the top navigation when scrolling
    # works only with permanentTopNav = true
    stickyNav = false

    # show a language chooser in the header
    showHeaderLanguageChooser = false

  # Content configuration
    # Enable an optional pinned page to display at the top of the index
#    pinnedPost = "/building-your-blog-the-geeky-way"
    # Set to true to pin only to the first page, false to all pages
#    pinOnlyToFirstPage = true

    # enable automatical localization of the article's PublishedDate with momentjs
    enableMomentJs = true

    # customize the date format | only works if momentjs is disabled | only works with English month names
    # you can customize it with the options you find here:
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    dateFormat = "2006-01-02"

    # display the estimated reading time for an article
    showReadingTime = false

  # Footer configuration
    showFooter = true

    # How many articles should be displayed at latest posts in the footer?
    # Set to -1 to hide the 'Latest Posts' column
    amountLatestPostsInFooter = 5

    # How many categories should be displayed in the footer section?
    # Set to -1 to hide the 'Categories' column
    amountCategoriesInFooter = 5

    # show a language chooser in the footer
    showFooterLanguageChooser = false

    # social media profile urls for the footer links
    showSocialMedia = true

    # define your links with FontAwesome 5 (only free icons are supported)
    # all icons https://fontawesome.com/icons?d=gallery&m=free
    # brand icons https://fontawesome.com/icons?d=gallery&s=brands&m=free
    socialMediaLinks = [
      { link = "https://www.linkedin.com/in/igorbaiborodine", icon = "fab fa-linkedin" },
      { link = "https://github.com/igor-baiborodine", icon = "fab fa-github" },
    ]

    # credits line configuration
    copyrightBy = "Igor Baiborodine"
    copyrightUseCurrentYear = true  # set to true to always display the current year in the copyright
    copyrightYearOverride = "2017"
    copyrightUrl = "https://github.com/igor-baiborodine"
    creditsText = "Powered by Bilberry Hugo Theme"
    creditsUrl = "https://github.com/Lednerb/bilberry-hugo-theme"


# customize your available languages for your multi-langual site
# or delete the [Languages] blog to use the theme with only one supported language
[Languages]
  [Languages.en]
    weight = 1

# don't change anything below
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"

[outputs]
  home = [ "HTML", "JSON", "RSS" ]
  page = [ "HTML" ]
